apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: getshorty-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: getshorty
spec:
  project: default
  destination:
    name: in-cluster
    namespace: prod
  source:
    path: .
    repoURL: https://github.com/maryia-devops-room/secure-helm.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
